GET http://localhost:8080/numbers

###

GET http://localhost:8080/numbers/A001AB

###

GET http://localhost:8080/numbers/0

###

POST http://localhost:8080/numbers
Content-Type: application/json

{
  "id": 0,
  "firstLetter": "А",
  "number": 500,
  "secondLetter": "У",
  "thirdLetter": "В"
}

###

GET http://localhost:8080/numbers/generate/

###

GET http://localhost:8080/numbers/generateRandom/

###

GET http://localhost:8080/numbers/generateNext/

###




GET project-platenumber.herokuapp.com/numbers




